[package]
name = "track"
edition = "2024"
publish = false

default-run = "track"

[features]
default = ["bundle", "import"]
bundle = ["dep:rust-embed", "dep:mime_guess"]
import = ["dep:chrono", "dep:serde_yaml", "dep:uuid"]

[dependencies]
api = { path = "../api", features = ["rand", "sqll"] }
iso639 = { path = "../iso639" }

anyhow = "1.0.102"
axum = "0.8.9"
bytes = "1.11.1"
clap = { version = "4.6.1", features = ["derive", "env"] }
lru = "0.18.0"
mime_guess = { version = "2.0.5", default-features = false, optional = true }
musli-web = { version = "0.4.3", default-features = false, features = ["axum08"] }
parking_lot = "0.12.5"
reqwest = { version = "0.13.4", default-features = false, features = ["query", "rustls", "stream"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
rust-embed = { version = "8.11.0", optional = true }
tempfile = "3.27.0"
tokio = { version = "1.52.3", features = ["full"] }
tower-http = { version = "0.6", features = ["cors"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio-util = "0.7.18"
jiff = "0.2.28"
sqll = { version = "0.14.2", features = ["bundled", "pool"] }
chrono = { version = "0.4.45", features = ["serde"], optional = true }
serde_yaml = { version = "0.9.34", optional = true }
uuid = { version = "1.23.3", default-features = false, optional = true, features = ["serde"] }
