[package]
name = "track"
edition = "2024"
publish = false

default-run = "track"

[features]
default = ["bundle", "import"]
bundle = ["dep:mime_guess"]
import = ["dep:chrono", "dep:serde_yaml", "dep:uuid"]

[[bin]]
name = "import"
required-features = ["import"]

[dependencies]
api = { path = "../api", features = ["rand", "sqll"] }
auth = { path = "../auth" }

anyhow = "1.0.104"
axum = "0.8.9"
base64 = "0.22.1"
bytes = "1.12.1"
cookie = "0.18.1"
clap = { version = "4.6.7", features = ["derive", "env"] }
lru = "0.18.5"
mime_guess = { version = "2.0.5", default-features = false, optional = true }
musli-web = { version = "0.4.10", default-features = false, features = ["axum08"] }
parking_lot = "0.12.5"
reqwest = { version = "0.13.5", default-features = false, features = ["query", "rustls", "stream"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
rust-embed = "8.12.0"
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["full"] }
tower-http = { version = "0.7.1", features = ["fs"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio-util = "0.7.19"
jiff = "0.2.37"
sqll = { version = "0.14.4", features = ["bundled", "pool"] }
chrono = { version = "0.4.45", features = ["serde"], optional = true }
serde_yaml = { version = "0.9.34", optional = true }
uuid = { version = "1.26.1", default-features = false, optional = true, features = ["serde"] }
leaky-bucket = "1.1.2"
rand = { version = "0.10.3", default-features = false }
