[package]
name = "frontend"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
api = { path = "../api", features = ["js", "yew"] }
iso639 = { path = "../iso639" }
iso3166 = { path = "../iso3166" }
locales = { path = "../locales" }

derive_more = { version = "2.1.1", features = ["display"] }
gloo = "0.12.0"
jiff = { version = "0.2.37", features = ["js"] }
jiff-tzdb = "0.1.8"
js-sys = "0.3.106"
musli-web = { version = "0.4.10", default-features = false, features = ["web03", "yew023"] }
serde = { version = "1.0.229", features = ["derive"] }
tracing = "0.1.44"
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.129"
yew = { version = "0.23.0", features = ["csr"] }
form_urlencoded = "1.2.2"

[dependencies.web-sys]
version = "0.3"
features = [
    "Clipboard",
    "CssStyleDeclaration",
    "Document",
    "DomRect",
    "DomTokenList",
    "Element",
    "EventTarget",
    "History",
    "HtmlCollection",
    "HtmlElement",
    "HtmlImageElement",
    "HtmlInputElement",
    "HtmlSelectElement",
    "KeyboardEvent",
    "Location",
    "MouseEvent",
    "Navigator",
    "Node",
    "NodeList",
    "PointerEvent",
    "Storage",
    "WheelEvent",
    "Window",
]
