[package]
name = "api"
edition = "2024"
publish = false

[features]
sqll = ["dep:sqll", "js"]
js = ["jiff/js"]
rand = ["dep:rand"]

[dependencies]
base64 = "0.22.1"
jiff = "0.2.28"
musli-core = { version = "0.1.4", default-features = false, features = ["alloc", "std"] }
musli-web = { version = "0.4.2", features = ["api"] }
rand = { version = "0.10.1", optional = true }
serde = { version = "1", features = ["derive"] }
sqll = { version = "0.13.2", optional = true }
