DROP TABLE IF EXISTS show_settings;
DROP TABLE IF EXISTS movie_settings;

ALTER TABLE shows DROP COLUMN language;
ALTER TABLE movies DROP COLUMN language;

ALTER TABLE shows ADD COLUMN language INTEGER NOT NULL DEFAULT 0;
ALTER TABLE movies ADD COLUMN language INTEGER NOT NULL DEFAULT 0;
