[package]
name = "server"
edition = "2024"
publish = false

[features]
default = ["bundle", "import"]
bundle = ["dep:rust-embed", "dep:mime_guess"]
import = ["dep:chrono", "dep:serde_yaml", "dep:uuid"]

[dependencies]
api = { path = "../api", features = ["rand", "sqll"] }

anyhow = "1"
axum = "0.8"
bytes = "1"
clap = { version = "4", features = ["derive", "env"] }
lru = "0.12"
mime_guess = { version = "2", default-features = false, optional = true }
musli-web = { version = "0.4.2", default-features = false, features = ["axum08"] }
parking_lot = "0.12"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rust-embed = { version = "8", optional = true }
tempfile = "3"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio-util = "0.7.18"
jiff = "0.2"
sqll = { version = "0.13.2", features = ["bundled"] }
chrono = { version = "0.4.45", features = ["serde"], optional = true }
serde_yaml = { version = "0.9.34", optional = true }
uuid = { version = "1.23.3", default-features = false, optional = true, features = ["serde"] }
iso639 = { version = "0.0.0", path = "../iso639" }
